Uses Docker for Cassandra integration tests and fixes OSGi
We ran into numerous problems relating to compilation and runtime of
Cassandra. This uses Docker instead, notably building an image at
runtime to test the tracing instrumentation.

diff --git a/build-bin/maven/maven_opts b/build-bin/maven/maven_opts
--- a/build-bin/maven/maven_opts
+++ b/build-bin/maven/maven_opts
@@ -13,9 +13,29 @@
 # the License.
 #
 
-set -ue
+# This script checks each variable value, so it isn't important to fail on unbound (set -u)
+set -e
 
-export MAVEN_OPTS="$($(dirname "$0")/maven_opts)"
+maven_project_basedir=${MAVEN_PROJECT_BASEDIR:-.}
+pom="${maven_project_basedir}/pom.xml"
 
-# Use a go-offline that properly works with multi-module builds
-./mvnw -q --batch-mode -nsu -Prelease de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
+# fail if there's no pom
+test -f "${pom}"
+
+arch=$(uname -m)
+case ${arch} in
+  arm64* )
+    arch=arm64
+    ;;
+  aarch64* )
+    arch=arm64
+    ;;
+esac
+
+maven_opts=""
+if [ ${arch} = "arm64" ] && [ -f /etc/alpine-release ]; then
+  # Defensively avoid arm64+alpine problems with posix_spawn
+  maven_opts="-Djdk.lang.Process.launchMechanism=vfork"
+fi
+
+echo ${maven_opts}
